#!/bin/sh
#
# Copyright (C) 2013 OpenMediaVault Plugin Developers
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_TRANSMISSIONBT_CONFIG=${OMV_TRANSMISSIONBT_CONFIG:-"/etc/transmission-daemon/settings.json"}
OMV_TRANSMISSIONBT_DEFAULT=${OMV_TRANSMISSIONBT_DEFAULT:-"/etc/default/transmission-daemon"}
OMV_TRANSMISSIONBT_RPCWHITELIST=${OMV_TRANSMISSIONBT_RPCWHITELIST:-"*.*.*.*"}
OMV_TRANSMISSIONBT_RPCWHITELISTENABLED=${OMV_TRANSMISSIONBT_RPCWHITELISTENABLED:-"true"}

# Create '/etc/default/transmission-daemon' file
cat <<EOF > ${OMV_TRANSMISSIONBT_DEFAULT}
# defaults for transmission-daemon
# sourced by /etc/init.d/transmission-daemon

EOF

xmlstarlet sel -t -m "//services/transmissionbt" \
  -v "concat('ENABLE_DAEMON=',enable)" -n \
  -o "CONFIG_DIR=\"/var/lib/transmission-daemon/info\"" -n \
  -o "OPTIONS=\"--config-dir \$CONFIG_DIR" \
  -i "rpcauthenticationrequired[. = '1']" -o " --auth" -b \
  -i "rpcauthenticationrequired[. = '0']" -o " --no-auth" -b \
  -o "\"" \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc >> ${OMV_TRANSMISSIONBT_DEFAULT}


BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_DOWNLOAD=${BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_DOWNLOAD=-m "//system/shares/sharedfolder[uuid=current()/modules/filesandlocations/paths/download/sharedfolderref]" -v "concat(//system/fstab/mntent[uuid=current()/mntentref]/dir,'/',reldirpath)" -b}
BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_INCOMPLETE=${BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_INCOMPLETE=-m "//system/shares/sharedfolder[uuid=current()/modules/filesandlocations/paths/incomplete/sharedfolderref]" -v "concat(//system/fstab/mntent[uuid=current()/mntentref]/dir,'/',reldirpath)" -b}
BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_WATCH=${BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_WATCH=-m "//system/shares/sharedfolder[uuid=current()/modules/filesandlocations/paths/watch/sharedfolderref]" -v "concat(//system/fstab/mntent[uuid=current()/mntentref]/dir,'/',reldirpath)" -b}


# Create '/etc/transmission-daemon/settings.json' file
xmlstarlet sel -t -m "//services/transmissionbt" \
  -o "{" -n \
  -o "\"download-dir\": \"" ${BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_DOWNLOAD} -o "/" -v modules/filesandlocations/paths/download/dir -o "\"," -n \
  -o "\"script-torrent-done-enabled\": " \
  -i "script-torrent-done-enabled[. = '0']" -o "false" -b \
  -i "script-torrent-done-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"script-torrent-done-filename\": \"',script-torrent-done-filename,'\",')" -n \
  -v "concat('\"encryption\": ',encryption,',')" -n \
  -o "\"dht-enabled:\": " \
  -i "dhtenabled[. = '0']" -o "false" -b \
  -i "dhtenabled[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"blocklist-enabled\": " \
  -i "blocklistenabled[. = '0']" -o "false" -b \
  -i "blocklistenabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"blocklist-url\": \"',blocklisturl,'\",')" -n \
  -o "\"pex-enabled\": " \
  -i "pexenabled[. = '0']" -o "false" -b \
  -i "pexenabled[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"lazy-bitfield-enabled\": " \
  -i "lazy-bitfield-enabled[. = '0']" -o "false" -b \
  -i "lazy-bitfield-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"umask\": ',umask,',')" -n \
  -o "\"lpd-enabled\": " \
  -i "lpd-enabled[. = '0']" -o "false" -b \
  -i "lpd-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"scrape-paused-torrents-enabled\": " \
  -i "scrape-paused-torrents-enabled[. = '0']" -o "false" -b \
  -i "scrape-paused-torrents-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"utp-enabled\": " \
  -i "utp-enabled[. = '0']" -o "false" -b \
  -i "utp-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"message-level\": ',message-level,',')" -n \
  -v "concat('\"cache-size-mb\": ',cache-size-mb,',')" -n \
  -v "concat('\"rpc-enabled\": ','true',',')" -n \
  -o "\"rpc-authentication-required\": " \
  -i "rpcauthenticationrequired[. = '0']" -o "false" -b \
  -i "rpcauthenticationrequired[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"rpc-password\": \"',rpcpassword,'\",')" -n \
  -v "concat('\"rpc-port\": ',rpcport,',')" -n \
  -v "concat('\"rpc-url\": \"',rpcurl,'\",')" -n \
  -v "concat('\"rpc-username\": \"',rpcusername,'\",')" -n \
  -o "\"rpc-whitelist\": \"${OMV_TRANSMISSIONBT_RPCWHITELIST}\"," -n \
  -o "\"rpc-whitelist-enabled\": ${OMV_TRANSMISSIONBT_RPCWHITELISTENABLED}," -n \
  -o "\"incomplete-dir-enabled\": " \
  -i "modules/filesandlocations/paths/incomplete/enabled[. = '0']" -o "false" -b \
  -i "modules/filesandlocations/paths/incomplete/enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"incomplete-dir\": \"" ${BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_INCOMPLETE} -o "/" -v modules/filesandlocations/paths/incomplete/dir -o "\"," -n \
  -o "\"watch-dir-enabled\": " \
  -i "modules/filesandlocations/paths/watch/enabled[. = '0']" -o "false" -b \
  -i "modules/filesandlocations/paths/watch/enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"watch-dir\": \"" ${BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_WATCH} -o "/" -v modules/filesandlocations/paths/watch/dir -o "\"," -n \
  -v "concat('\"preallocation\": ',modules/filesandlocations/preallocation,',')" -n \
  -o "\"rename-partial-files\": " \
  -i "modules/filesandlocations/rename-partial-files[. = '0']" -o "false" -b \
  -i "modules/filesandlocations/rename-partial-files[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"start-added-torrents\": " \
  -i "modules/filesandlocations/start-added-torrents[. = '0']" -o "false" -b \
  -i "modules/filesandlocations/start-added-torrents[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"trash-original-torrent-files\": " \
  -i "modules/filesandlocations/trash-original-torrent-files[. = '0']" -o "false" -b \
  -i "modules/filesandlocations/trash-original-torrent-files[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"speed-limit-down\": ',modules/bandwidth/speed-limit-down,',')" -n \
  -o "\"speed-limit-down-enabled\": " \
  -i "modules/bandwidth/speed-limit-down-enabled[. = '0']" -o "false" -b \
  -i "modules/bandwidth/speed-limit-down-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"speed-limit-up\": ',modules/bandwidth/speed-limit-up,',')" -n \
  -o "\"speed-limit-up-enabled\": " \
  -i "modules/bandwidth/speed-limit-up-enabled[. = '0']" -o "false" -b \
  -i "modules/bandwidth/speed-limit-up-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"upload-slots-per-torrent\": ',modules/bandwidth/upload-slots-per-torrent,',')" -n \
  -o "\"alt-speed-enabled\": " \
  -i "modules/bandwidth/alt-speed-enabled[. = '0']" -o "false" -b \
  -i "modules/bandwidth/alt-speed-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"alt-speed-up\": ',modules/bandwidth/alt-speed-up,',')" -n \
  -v "concat('\"alt-speed-down\": ',modules/bandwidth/alt-speed-down,',')" -n \
  -o "\"queue-stalled-enabled\": " \
  -i "modules/queuing/queue-stalled-enabled[. = '0']" -o "false" -b \
  -i "modules/queuing/queue-stalled-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"queue-stalled-minutes\": ',modules/queuing/queue-stalled-minutes,',')" -n \
  -o "\"download-queue-enabled\": " \
  -i "modules/queuing/download-queue-enabled[. = '0']" -o "false" -b \
  -i "modules/queuing/download-queue-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"download-queue-size\": ',modules/queuing/download-queue-size,',')" -n \
  -o "\"seed-queue-enabled\": " \
  -i "modules/queuing/seed-queue-enabled[. = '0']" -o "false" -b \
  -i "modules/queuing/seed-queue-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"seed-queue-size\": ',modules/queuing/seed-queue-size,',')" -n \
  -v "concat('\"bind-address-ipv4\": \"',modules/peer/bind-address-ipv4,'\",')" -n \
  -v "concat('\"bind-address-ipv6\": \"',modules/peer/bind-address-ipv6,'\",')" -n \
  -v "concat('\"peer-limit-global\": ',modules/peer/peer-limit-global,',')" -n \
  -v "concat('\"peer-limit-per-torrent\": ',modules/peer/peer-limit-per-torrent,',')" -n \
  -v "concat('\"peer-socket-tos\": \"',modules/peer/peer-socket-tos,'\",')" -n \
  -v "concat('\"peer-port\": ',modules/peer/peer-port,',')" -n \
  -v "concat('\"peer-port-random-high\": ',modules/peer/peer-port-random-high,',')" -n \
  -v "concat('\"peer-port-random-low\": ',modules/peer/peer-port-random-low,',')" -n \
  -o "\"port-forwarding-enabled\": " \
  -i "modules/peer/port-forwarding-enabled[. = '0']" -o "false" -b \
  -i "modules/peer/port-forwarding-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"peer-port-random-on-start\": " \
  -i "modules/peer/peer-port-random-on-start[. = '0']" -o "false" -b \
  -i "modules/peer/peer-port-random-on-start[. = '1']" -o "true" -b \
  -o "," -n \
  -o "\"alt-speed-time-enabled\": " \
  -i "modules/scheduling/alt-speed-time-enabled[. = '0']" -o "false" -b \
  -i "modules/scheduling/alt-speed-time-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"alt-speed-time-begin\": ',modules/scheduling/alt-speed-time-begin,',')" -n \
  -v "concat('\"alt-speed-time-end\": ',modules/scheduling/alt-speed-time-end,',')" -n \
  -v "concat('\"alt-speed-time-day\": ',modules/scheduling/alt-speed-time-day,',')" -n \
  -v "concat('\"idle-seeding-limit\": ',modules/scheduling/idle-seeding-limit,',')" -n \
  -o "\"idle-seeding-limit-enabled\": " \
  -i "modules/scheduling/idle-seeding-limit-enabled[. = '0']" -o "false" -b \
  -i "modules/scheduling/idle-seeding-limit-enabled[. = '1']" -o "true" -b \
  -o "," -n \
  -v "concat('\"ratio-limit\": ',modules/scheduling/ratio-limit,',')" -n \
  -o "\"ratio-limit-enabled\": " \
  -i "modules/scheduling/ratio-limit-enabled[. = '0']" -o "false" -b \
  -i "modules/scheduling/ratio-limit-enabled[. = '1']" -o "true" -b \
  -o "}" \
  ${OMV_CONFIG_FILE} | xmlstarlet unesc > ${OMV_TRANSMISSIONBT_CONFIG}


enable=$(omv_config_get "//services/transmissionbt/enable")

watch_dir_enable=$(omv_config_get "//services/transmissionbt/modules/filesandlocations/paths/watch/enabled")
if [ 1 = ${enable} -a  1 = ${watch_dir_enable} ]; then
	watch_dir=$(omv_config_get "//services/transmissionbt/modules/filesandlocations/paths/watch/dir")
	watch_dir_full=`xmlstarlet sel -t -m "//services/transmissionbt" ${BT_XMLSTARLET_GET_SHAREDFOLDER_PATH_WATCH} -o "/" -v "modules/filesandlocations/paths/watch/dir" ${OMV_CONFIG_FILE}`
	mkdir -p ${watch_dir_full}
fi

script_torrent_done_enabled=$(omv_config_get "//services/transmissionbt/script-torrent-done-enabled")
if [ 1 = ${enable} -a  1 = ${script_torrent_done_enabled} ]; then
	script_torrent_done_filename=$(omv_config_get "//services/transmissionbt/script-torrent-done-filename")
	chmod +x ${script_torrent_done_filename}
fi

# Create transmission cron file
blocklistsyncenabled=$(omv_config_get "//services/transmissionbt/blocklistsyncenabled")
blocklistsyncfrequency=$(omv_config_get "//services/transmissionbt/blocklistsyncfrequency")
cronfile="/etc/cron.${blocklistsyncfrequency}/transmissionbt"

# Remove all previous cron files. Due we do not know if the frequency
# have been modified we have to scan all /etc/cron.xxx directories.
for crondir in $(ls -d /etc/cron.*ly)
do
	[ -e "${crondir}/transmissionbt" ] && rm "${crondir}/transmissionbt"
done

if [ 1 = ${enable} -a 1 = ${blocklistsyncenabled} ]; then
	rpcusername=$(omv_config_get "//services/transmissionbt/rpcusername")
	rpcpassword=$(omv_config_get "//services/transmissionbt/rpcpassword")
	cat <<EOF > ${cronfile}
#!/bin/sh
#
# cron script to update TransmissionBT blocklists
# by Volker Theile <volker.theile@openmediavault.org>
# by Marcel Beck <marcel.beck@mbeck.org>

set -e

transmission-remote -n ${rpcusername}:${rpcpassword} --blocklist-update

EOF
	chmod 755 ${cronfile}
fi
