#!/bin/sh
#
# Copyright (C) 2013 OpenMediaVault Plugin Developers
# Copyright (c) 2012 Marcel Beck
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

# Create the configuration files
omv-mkconf transmissionbt

# Enable/disable service
if [ "$(omv_config_get "//services/transmissionbt/enable")" = "0" ]; then
	update-rc.d transmission-daemon disable 2>&1
else
	update-rc.d transmission-daemon enable 2>&1
fi

exit 0
